services:
  database:
    image: "postgres:16"
    environment:
      POSTGRES_USER: akitha
      POSTGRES_PASSWORD: ubuntu2436
      POSTGRES_DB: shelter
    volumes:
      - database_data:/var/lib/postgresql/data  
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  
  etl:
    build: .
    command: https://shelterdata.s3.amazonaws.com/shelter1000.csv
    depends_on:
      - database   

volumes:
  database_data:

  